WITH source AS (

    SELECT * FROM {{ source('covid19_symptom_search', 'symptom_search_country_weekly') }}

)


SELECT
  CAST(date AS DATE) AS date,
  country_region,
  symptom,
  CAST(symptom_proba AS FLOAT64) AS symptom_proba
FROM
  source
UNPIVOT(
    symptom_proba FOR symptom IN (
    symptom_abdominal_obesity
    ,symptom_abdominal_pain
    ,symptom_acne
    ,symptom_actinic_keratosis
    ,symptom_acute_bronchitis
    ,symptom_adrenal_crisis
    ,symptom_ageusia
    ,symptom_alcoholism
    ,symptom_allergic_conjunctivitis
    ,symptom_allergy
    ,symptom_amblyopia
    ,symptom_amenorrhea
    ,symptom_amnesia
    ,symptom_anal_fissure
    ,symptom_anaphylaxis
    ,symptom_anemia
    ,symptom_angina_pectoris
    ,symptom_angioedema
    ,symptom_angular_cheilitis
    ,symptom_anosmia
    ,symptom_anxiety
    ,symptom_aphasia
    ,symptom_aphonia
    ,symptom_apnea
    ,symptom_arthralgia
    ,symptom_arthritis
    ,symptom_ascites
    ,symptom_asperger_syndrome
    ,symptom_asphyxia
    ,symptom_asthma
    ,symptom_astigmatism
    ,symptom_ataxia
    ,symptom_atheroma
    ,symptom_attention_deficit_hyperactivity_disorder
    ,symptom_auditory_hallucination
    ,symptom_autoimmune_disease
    ,symptom_avoidant_personality_disorder
    ,symptom_back_pain
    ,symptom_bacterial_vaginosis
    ,symptom_balance_disorder
    ,symptom_beau_s_lines
    ,symptom_bell_s_palsy
    ,symptom_biliary_colic
    ,symptom_binge_eating
    ,symptom_bleeding
    ,symptom_bleeding_on_probing
    ,symptom_blepharospasm
    ,symptom_bloating
    ,symptom_blood_in_stool
    ,symptom_blurred_vision
    ,symptom_blushing
    ,symptom_boil
    ,symptom_bone_fracture
    ,symptom_bone_tumor
    ,symptom_bowel_obstruction
    ,symptom_bradycardia
    ,symptom_braxton_hicks_contractions
    ,symptom_breakthrough_bleeding
    ,symptom_breast_pain
    ,symptom_bronchitis
    ,symptom_bruise
    ,symptom_bruxism
    ,symptom_bunion
    ,symptom_burn
    ,symptom_burning_chest_pain
    ,symptom_burning_mouth_syndrome
    ,symptom_candidiasis
    ,symptom_canker_sore
    ,symptom_cardiac_arrest
    ,symptom_carpal_tunnel_syndrome
    ,symptom_cataplexy
    ,symptom_cataract
    ,symptom_chancre
    ,symptom_cheilitis
    ,symptom_chest_pain
    ,symptom_chills
    ,symptom_chorea
    ,symptom_chronic_pain
    ,symptom_cirrhosis
    ,symptom_cleft_lip_and_cleft_palate
    ,symptom_clouding_of_consciousness
    ,symptom_cluster_headache
    ,symptom_colitis
    ,symptom_coma
    ,symptom_common_cold
    ,symptom_compulsive_behavior
    ,symptom_compulsive_hoarding
    ,symptom_confusion
    ,symptom_congenital_heart_defect
    ,symptom_conjunctivitis
    ,symptom_constipation
    ,symptom_convulsion
    ,symptom_cough
    ,symptom_crackles
    ,symptom_cramp
    ,symptom_crepitus
    ,symptom_croup
    ,symptom_cyanosis
    ,symptom_dandruff
    ,symptom_delayed_onset_muscle_soreness
    ,symptom_dementia
    ,symptom_dentin_hypersensitivity
    ,symptom_depersonalization
    ,symptom_depression
    ,symptom_dermatitis
    ,symptom_desquamation
    ,symptom_developmental_disability
    ,symptom_diabetes
    ,symptom_diabetic_ketoacidosis
    ,symptom_diarrhea
    ,symptom_dizziness
    ,symptom_dry_eye_syndrome
    ,symptom_dysautonomia
    ,symptom_dysgeusia
    ,symptom_dysmenorrhea
    ,symptom_dyspareunia
    ,symptom_dysphagia
    ,symptom_dysphoria
    ,symptom_dystonia
    ,symptom_dysuria
    ,symptom_ear_pain
    ,symptom_eczema
    ,symptom_edema
    ,symptom_encephalitis
    ,symptom_encephalopathy
    ,symptom_epidermoid_cyst
    ,symptom_epilepsy
    ,symptom_epiphora
    ,symptom_erectile_dysfunction
    ,symptom_erythema
    ,symptom_erythema_chronicum_migrans
    ,symptom_esophagitis
    ,symptom_excessive_daytime_sleepiness
    ,symptom_eye_pain
    ,symptom_eye_strain
    ,symptom_facial_nerve_paralysis
    ,symptom_facial_swelling
    ,symptom_fasciculation
    ,symptom_fatigue
    ,symptom_fatty_liver_disease
    ,symptom_fecal_incontinence
    ,symptom_fever
    ,symptom_fibrillation
    ,symptom_fibrocystic_breast_changes
    ,symptom_fibromyalgia
    ,symptom_flatulence
    ,symptom_floater
    ,symptom_focal_seizure
    ,symptom_folate_deficiency
    ,symptom_food_craving
    ,symptom_food_intolerance
    ,symptom_frequent_urination
    ,symptom_gastroesophageal_reflux_disease
    ,symptom_gastroparesis
    ,symptom_generalized_anxiety_disorder
    ,symptom_generalized_tonic_clonic_seizure
    ,symptom_genital_wart
    ,symptom_gingival_recession
    ,symptom_gingivitis
    ,symptom_globus_pharyngis
    ,symptom_goitre
    ,symptom_gout
    ,symptom_grandiosity
    ,symptom_granuloma
    ,symptom_guilt
    ,symptom_hair_loss
    ,symptom_halitosis
    ,symptom_hay_fever
    ,symptom_headache
    ,symptom_heart_arrhythmia
    ,symptom_heart_murmur
    ,symptom_heartburn
    ,symptom_hematochezia
    ,symptom_hematoma
    ,symptom_hematuria
    ,symptom_hemolysis
    ,symptom_hemoptysis
    ,symptom_hemorrhoids
    ,symptom_hepatic_encephalopathy
    ,symptom_hepatitis
    ,symptom_hepatotoxicity
    ,symptom_hiccup
    ,symptom_hip_pain
    ,symptom_hives
    ,symptom_hot_flash
    ,symptom_hydrocephalus
    ,symptom_hypercalcaemia
    ,symptom_hypercapnia
    ,symptom_hypercholesterolemia
    ,symptom_hyperemesis_gravidarum
    ,symptom_hyperglycemia
    ,symptom_hyperkalemia
    ,symptom_hyperlipidemia
    ,symptom_hypermobility
    ,symptom_hyperpigmentation
    ,symptom_hypersomnia
    ,symptom_hypertension
    ,symptom_hyperthermia
    ,symptom_hyperthyroidism
    ,symptom_hypertriglyceridemia
    ,symptom_hypertrophy
    ,symptom_hyperventilation
    ,symptom_hypocalcaemia
    ,symptom_hypochondriasis
    ,symptom_hypoglycemia
    ,symptom_hypogonadism
    ,symptom_hypokalemia
    ,symptom_hypomania
    ,symptom_hyponatremia
    ,symptom_hypotension
    ,symptom_hypothyroidism
    ,symptom_hypoxemia
    ,symptom_hypoxia
    ,symptom_impetigo
    ,symptom_implantation_bleeding
    ,symptom_impulsivity
    ,symptom_indigestion
    ,symptom_infection
    ,symptom_inflammation
    ,symptom_inflammatory_bowel_disease
    ,symptom_ingrown_hair
    ,symptom_insomnia
    ,symptom_insulin_resistance
    ,symptom_intermenstrual_bleeding
    ,symptom_intracranial_pressure
    ,symptom_iron_deficiency
    ,symptom_irregular_menstruation
    ,symptom_itch
    ,symptom_jaundice
    ,symptom_kidney_failure
    ,symptom_kidney_stone
    ,symptom_knee_pain
    ,symptom_kyphosis
    ,symptom_lactose_intolerance
    ,symptom_laryngitis
    ,symptom_leg_cramps
    ,symptom_lesion
    ,symptom_leukorrhea
    ,symptom_lightheadedness
    ,symptom_low_back_pain
    ,symptom_low_grade_fever
    ,symptom_lymphedema
    ,symptom_major_depressive_disorder
    ,symptom_malabsorption
    ,symptom_male_infertility
    ,symptom_manic_disorder
    ,symptom_melasma
    ,symptom_melena
    ,symptom_meningitis
    ,symptom_menorrhagia
    ,symptom_middle_back_pain
    ,symptom_migraine
    ,symptom_milium
    ,symptom_mitral_insufficiency
    ,symptom_mood_disorder
    ,symptom_mood_swing
    ,symptom_morning_sickness
    ,symptom_motion_sickness
    ,symptom_mouth_ulcer
    ,symptom_muscle_atrophy
    ,symptom_muscle_weakness
    ,symptom_myalgia
    ,symptom_mydriasis
    ,symptom_myocardial_infarction
    ,symptom_myoclonus
    ,symptom_nasal_congestion
    ,symptom_nasal_polyp
    ,symptom_nausea
    ,symptom_neck_mass
    ,symptom_neck_pain
    ,symptom_neonatal_jaundice
    ,symptom_nerve_injury
    ,symptom_neuralgia
    ,symptom_neutropenia
    ,symptom_night_sweats
    ,symptom_night_terror
    ,symptom_nocturnal_enuresis
    ,symptom_nodule
    ,symptom_nosebleed
    ,symptom_nystagmus
    ,symptom_obesity
    ,symptom_onychorrhexis
    ,symptom_oral_candidiasis
    ,symptom_orthostatic_hypotension
    ,symptom_osteopenia
    ,symptom_osteophyte
    ,symptom_osteoporosis
    ,symptom_otitis
    ,symptom_otitis_externa
    ,symptom_otitis_media
    ,symptom_pain
    ,symptom_palpitations
    ,symptom_panic_attack
    ,symptom_papule
    ,symptom_paranoia
    ,symptom_paresthesia
    ,symptom_pelvic_inflammatory_disease
    ,symptom_pericarditis
    ,symptom_periodontal_disease
    ,symptom_periorbital_puffiness
    ,symptom_peripheral_neuropathy
    ,symptom_perspiration
    ,symptom_petechia
    ,symptom_phlegm
    ,symptom_photodermatitis
    ,symptom_photophobia
    ,symptom_photopsia
    ,symptom_pleural_effusion
    ,symptom_pleurisy
    ,symptom_pneumonia
    ,symptom_podalgia
    ,symptom_polycythemia
    ,symptom_polydipsia
    ,symptom_polyneuropathy
    ,symptom_polyuria
    ,symptom_poor_posture
    ,symptom_post_nasal_drip
    ,symptom_postural_orthostatic_tachycardia_syndrome
    ,symptom_prediabetes
    ,symptom_proteinuria
    ,symptom_pruritus_ani
    ,symptom_psychosis
    ,symptom_ptosis
    ,symptom_pulmonary_edema
    ,symptom_pulmonary_hypertension
    ,symptom_purpura
    ,symptom_pus
    ,symptom_pyelonephritis
    ,symptom_radiculopathy
    ,symptom_rectal_pain
    ,symptom_rectal_prolapse
    ,symptom_red_eye
    ,symptom_renal_colic
    ,symptom_restless_legs_syndrome
    ,symptom_rheum
    ,symptom_rhinitis
    ,symptom_rhinorrhea
    ,symptom_rosacea
    ,symptom_round_ligament_pain
    ,symptom_rumination
    ,symptom_scar
    ,symptom_sciatica
    ,symptom_scoliosis
    ,symptom_seborrheic_dermatitis
    ,symptom_self_harm
    ,symptom_sensitivity_to_sound
    ,symptom_sexual_dysfunction
    ,symptom_shallow_breathing
    ,symptom_sharp_pain
    ,symptom_shivering
    ,symptom_shortness_of_breath
    ,symptom_shyness
    ,symptom_sinusitis
    ,symptom_skin_condition
    ,symptom_skin_rash
    ,symptom_skin_tag
    ,symptom_skin_ulcer
    ,symptom_sleep_apnea
    ,symptom_sleep_deprivation
    ,symptom_sleep_disorder
    ,symptom_snoring
    ,symptom_sore_throat
    ,symptom_spasticity
    ,symptom_splenomegaly
    ,symptom_sputum
    ,symptom_stomach_rumble
    ,symptom_strabismus
    ,symptom_stretch_marks
    ,symptom_stridor
    ,symptom_stroke
    ,symptom_stuttering
    ,symptom_subdural_hematoma
    ,symptom_suicidal_ideation
    ,symptom_swelling
    ,symptom_swollen_feet
    ,symptom_swollen_lymph_nodes
    ,symptom_syncope
    ,symptom_tachycardia
    ,symptom_tachypnea
    ,symptom_telangiectasia
    ,symptom_tenderness
    ,symptom_testicular_pain
    ,symptom_throat_irritation
    ,symptom_thrombocytopenia
    ,symptom_thyroid_nodule
    ,symptom_tic
    ,symptom_tinnitus
    ,symptom_tonsillitis
    ,symptom_toothache
    ,symptom_tremor
    ,symptom_trichoptilosis
    ,symptom_tumor
    ,symptom_type_2_diabetes
    ,symptom_unconsciousness
    ,symptom_underweight
    ,symptom_upper_respiratory_tract_infection
    ,symptom_urethritis
    ,symptom_urinary_incontinence
    ,symptom_urinary_tract_infection
    ,symptom_urinary_urgency
    ,symptom_uterine_contraction
    ,symptom_vaginal_bleeding
    ,symptom_vaginal_discharge
    ,symptom_vaginitis
    ,symptom_varicose_veins
    ,symptom_vasculitis
    ,symptom_ventricular_fibrillation
    ,symptom_ventricular_tachycardia
    ,symptom_vertigo
    ,symptom_viral_pneumonia
    ,symptom_visual_acuity
    ,symptom_vomiting
    ,symptom_wart
    ,symptom_water_retention
    ,symptom_weakness
    ,symptom_weight_gain
    ,symptom_wheeze
    ,symptom_xeroderma
    ,symptom_xerostomia
    ,symptom_yawn
    ,symptom_hyperhidrosis
    ,symptom_pancreatitis
))